# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1taYSkyAz0_ON11DkMK8eQbJPrYk-ImUL
"""

def terceira_funcao():
    print("-> Dentro da terceira_funcao(): retornando o valor 10.")
    return 10

def segunda_funcao():
    print("-> Dentro da segunda_funcao(): chamando a terceira_funcao().")
    valor_recebido = terceira_funcao()
    print("<- De volta à segunda_funcao(): processando o valor recebido.")
    resultado_processado = valor_recebido * 5
    return resultado_processado

def main():
    print("-> Dentro da main(): chamando a segunda_funcao().")
    resultado_final = segunda_funcao()
    print("<- De volta à main(): imprimindo o resultado final.")
    print(f"O resultado final é: {resultado_final}")

if __name__ == "__main__":
    main()

def contagem(n):
    # Caso base: para a recursão quando n for negativo.
    if n < 0:
        return
    # Imprime o valor atual de n.
    print(n)

    # Caso recursivo: chama a si mesma com n-1.
    contagem(n - 1)

# Mostra a saída para contagem(5).
print("Iniciando a contagem regressiva de 5:")
contagem(5)

def fatorial(n):
    # Caso base: se n for 0 ou 1, o fatorial é 1.
    if n == 0 or n == 1:
        return 1
    # Caso recursivo: n * fatorial(n-1).
    else:
        return n * fatorial(n - 1)

resultado = fatorial(3)
print(f"O fatorial de 3 é: {resultado}")