# -*- coding: utf-8 -*-
"""Atividade 08.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16cbmzdSg0pC7aG-ZB4Q6B-8rcSG7pFh9
"""

def multiplica(a,b):
  return a * b

def soma(a,b):
  return a + b

def calcula():
  x = multiplica(2,3)
  y = soma(x,4)
  return y

def main():
  resultado = calcula()
  print("Resultado final: ", resultado)

main()

"""A execução começa com a chamada da função main().

1) main() chama calcula(): Dentro de main(), a linha resultado = calcula() inicia
uma chamada para a função calcula().

2) calcula() chama multiplica(): Dentro de calcula(), a linha x = multiplica(2,3) inicia uma chamada para a função multiplica() com os argumentos 2 e 3.

3) calcula() chama soma(): Após multiplica() retornar, a linha y = soma(x,4) inicia uma chamada para a função soma() com os argumentos x (que é o resultado de multiplica(2,3), ou seja, 6) e 4.

4) main() chama print(): Após calcula() retornar, a função main() continua e chama a função embutida print() para exibir o resultado.

"""

+-----------------+
| print()         |  (prestes a ser chamada por main depois que calcula retornar)
+-----------------+
| soma(a=6, b=4)  |  (atualmente em execução)
+-----------------+
| calcula()       |  (esperando soma retornar)
+-----------------+
| main()          |  (esperando calcula retornar)
+-----------------+
| <escopo global> |  (o ambiente do programa principal)
+-----------------+

def modifica_numero(x):
  x = x + 10
  print(f"Dentro da função: {x}")

def modifica_lista(lista):
  lista.append(100)
  print(f"Dentro da função: {lista}")

# o começo do programa é na váriavel número
numero = 5

# o começo da segunda parte do programa é na lista
lista = [1, 2, 3]

print(f"Antes de chamar a função: {numero}")
# logo após ela acessa a função modifica_numero e nessa função
# ele irá executar a soma x = 5 + 10 = 15
modifica_numero(numero)
# aqui o número chegará modificado, com o novo resultado
print(f"Depois de chamar a função: {numero}")

print(f"Antes de chamar a função: {lista}")
# logo após a lista acessa a função modifica_lista e nessa função
# ele irá adicionar o número 100 no final da lista
modifica_lista(lista)
# aqui irá mostrar o conteúdo da nova lista
print(f"Depois de chamar a função: {lista}")

"""------------ NÚMERO --------------
a diferença em python é que números inteiros são imutáveis
logo quando modificamos o x dentro da função (x = x + 10)
não estamos alterando o valor da váriavel, mas sim criando um
novo objeto inteiro com o novo valor e atribuindo a variável local x.

Quando a função termina, a variável local x é destruída,
e a variável original numero fora da função mantém seu valor original (5).

Antes de chamar a função: 5
Dentro da função: 15
Depois de chamar a função: 5

----------- LISTA ---------------

as listas em python são mutáveis, significa que quando modificamos a lista
dentro da função, qualquer alteração feita na lista dentro da função afetará a lista original fora da função.
"""