# -*- coding: utf-8 -*-
"""Atividade 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Qk_xGHUxtVZcojRKQ5yrp9YLBMPGyTd
"""

# Simulação de controle de acesso ao Restaurante Universitário (RU) da UFRGS

alunos = [
    {
        "matricula": "UFRGS2025001",
        "nome": "Alice Silva",
        "creditos": 5
    },
    {
        "matricula": "UFRGS2025002",
        "nome": "Bruno Costa",
        "creditos": 1
    },
    {
        "matricula": "UFRGS2025003",
        "nome": "Carla Mendes",
        "creditos": 0
    },
    {
        "matricula": "UFRGS2025004",
        "nome": "Diego Souza",
        "creditos": 10
    }
]

ru = {
    "nome": "Restaurante Universitário UFRGS",
    "total_atendimentos": 0,
    "total_negados_sem_credito": 0
}

def encontrar_aluno(matricula):
    for aluno in alunos:
        if aluno["matricula"] == matricula:
            return aluno
    return None

def usar_refeicao(matricula):
    print(f"--- Tentativa de acesso com a matrícula: {matricula} ---")
    aluno = encontrar_aluno(matricula)

    if aluno:
        if aluno["creditos"] >= 1:
            aluno["creditos"] -= 1
            ru["total_atendimentos"] += 1
            print(f"Acesso liberado para: {aluno['nome']}. Bom apetite!")
        else:
            ru["total_negados_sem_credito"] += 1
            print(f"Acesso negado para: {aluno['nome']}. Créditos insuficientes. Por favor, faça uma recarga.")
    else:
        print(f"Erro: Matrícula '{matricula}' não encontrada no sistema.")

print(">>> INÍCIO DA SIMULAÇÃO DE ENTRADA NO RU <<<\n")

eventos = [
    "UFRGS2025001",
    "UFRGS2025002",
    "UFRGS2025003",
    "UFRGS2025001",
    "UFRGS2025999",
    "UFRGS2025004",
    "UFRGS2025002"
]

for matricula_evento in eventos:
    usar_refeicao(matricula_evento)
    print("-" * 50)

print("\n>>> RELATÓRIO FINAL DA SIMULAÇÃO <<<\n")

print(f"Total de atendimentos liberados: {ru['total_atendimentos']}")
print(f"Total de atendimentos negados por falta de crédito: {ru['total_negados_sem_credito']}\n")

print("Créditos remanescentes por aluno:")
for aluno in alunos:
    print(f"- {aluno['nome']} (Matrícula: {aluno['matricula']}): {aluno['creditos']} crédito(s)")