# -*- coding: utf-8 -*-
"""Atividade 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DX-bvefsxxbSlsQAhgDFw4PgvDcDKs1v
"""

usuarios = [
{"tipo": "aluno", "matricula": "A001", "historico_emprestimos": []},
{"tipo": "professor", "matricula": "P001", "historico_emprestimos": []},
{"tipo": "funcionario", "matricula": "F001", "historico_emprestimos": []}
]

print("lista inicial de usuarios:")
for u in usuarios:
    print(u)
print()

livros = [
{"isbn": "12345", "titulo": "python para iniciantes", "disponivel": True, "localizacao": "estante A", "prazo_devolucao": None},
{"isbn": "67890", "titulo": "modelagem e simulacao", "disponivel": True, "localizacao": "estante B", "prazo_devolucao": None}
]

print("lista inicial de livros:")
for l in livros:
    print(l)
print()

bibliotecaria = [
{"nome": "joao", "turno": "manha", "especializacao": None},
{"nome": "maria", "turno": "tarde", "especializacao": None}
]

print("lista inicial de bibliotecarias:")
for b in bibliotecaria:
    print(b)
print()

emprestimos_ativos = {}

def encontra_usuario(matricula):
    for u in usuarios:
        if u["matricula"] == matricula:
            print("usuario encontrado:", u)
            return u
    print("usuario com matricula", matricula, "nao encontrado.")
    return None

def encontra_livro(isbn):
    for livro in livros:
        if livro["isbn"] == isbn:
            print("livro encontrado:", livro)
            return livro
    print("livro com isbn", isbn, "nao encontrado.")
    return None

def emprestar_livro(matricula, isbn):
    usuario = encontra_usuario(matricula)
    livro = encontra_livro(isbn)
    print()
    if usuario and livro:
        if livro["disponivel"]:
            livro["disponivel"] = False
            if livro not in usuario["historico_emprestimos"]:
                usuario["historico_emprestimos"].append(livro)
            emprestimos_ativos[isbn] = matricula
            print(f"livro '{livro['titulo']}' emprestado para o usuario '{usuario['matricula']}'.")
        else:
            print(f"livro '{livro['titulo']}' nao esta disponivel para emprestimo.")
    elif not usuario:
        print("emprestimo nao realizado: usuario nao encontrado.")
    elif not livro:
        print("emprestimo nao realizado: livro nao encontrado.")

def devolver_livro(matricula, isbn):
    usuario = encontra_usuario(matricula)
    livro = encontra_livro(isbn)
    print()
    if usuario and livro:
        if isbn in emprestimos_ativos and emprestimos_ativos[isbn] == matricula:
            livro["disponivel"] = True
            del emprestimos_ativos[isbn]
            print(f"livro '{livro['titulo']}' devolvido pelo usuario '{usuario['matricula']}'.")
        else:
            print(f"livro '{livro['titulo']}' nao esta emprestado para o usuario '{usuario['matricula']}'.")

def verificar_situacao_livro(isbn):
    print()
    livro = encontra_livro(isbn)
    if livro:
        if livro["disponivel"]:
            print(f"livro '{livro['titulo']}' esta disponivel para emprestimo.")
        else:
            print(f"livro '{livro['titulo']}' nao esta disponivel para emprestimo.")

def resumo_atual():
    print()
    print("resumo atual:")
    for livro in livros:
        status = "disponivel" if livro["disponivel"] else f"emprestado para {emprestimos_ativos.get(livro['isbn'], 'desconhecido')}"
        print(f"{livro['titulo']} (isbn {livro['isbn']}): {status}")

def listar_historico_emprestimo():
    print()
    print("historico de emprestimos:")
    for usuario in usuarios:
        print(f"usuario: {usuario['matricula']}")
        print("livros emprestados:")
        for livro in usuario["historico_emprestimos"]:
            print(f"- {livro['titulo']} (isbn: {livro['isbn']})")
        print()

print()
print("** inicio da simulacao da biblioteca **")
print()

emprestar_livro("A001", "12345")
emprestar_livro("P001", "67890")
emprestar_livro("A001", "67890")
devolver_livro("A001", "12345")
emprestar_livro("F001", "12345")

print()
print("** estado final da simulacao **")

print()
print("lista dos livros com seus status (disponivel ou emprestado):")
for livro in livros:
    status = "disponivel" if livro["disponivel"] else "emprestado"
    print(f"- {livro['titulo']} (isbn: {livro['isbn']}): {status}")

print()
print("lista dos usuarios com seus historicos de emprestimos:")
for usuario in usuarios:
    isbns = [livro["isbn"] for livro in usuario["historico_emprestimos"]]
    print(f"- {usuario['tipo']} {usuario['matricula']}: emprestimos: {isbns}")

print()
print("lista dos emprestimos ativos, mostrando o titulo do livro, o tipo do usuario e a matricula:")
print("- emprestimos ativos:")
for isbn, matricula in emprestimos_ativos.items():
    livro = encontra_livro(isbn)
    usuario = encontra_usuario(matricula)
    print(f"- livro: '{livro['titulo']}' (isbn: {isbn}) emprestado para {usuario['tipo']} (matricula: {matricula})")

print()
print("** simulacao finalizada **")