# -*- coding: utf-8 -*-
"""trabalho 7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aaAzGngq6GtvAvDT3IgeKJgry7p0WYBL

Programa 1: Análise da Fila do Restaurante Universitário (RU)
"""

#Este código simula e analisa o fluxo de pessoas
#no restaurante da universidade durante o horário de pico do almoço.
import numpy as np
import matplotlib.pyplot as plt

def analisar_fila(dados_servico):

  # ----- extração dos dados -----
  nome_servico = dados_servico["nome_servico"]
  horario_obs = dados_servico["horario_observacao"]
  num_servidores = dados_servico["numero_servidores"]
  chegadas_por_minuto = dados_servico["chegadas"]
  tempos_atendimento = dados_servico["atendimentos"]

  # ----- cálculos -----
  total_chegadas = sum(chegadas_por_minuto)
  tempo_medio_atendimento = np.mean(tempos_atendimento)

  # ----- taxa de chegadas (pessoas por minuto)
  lambda_val = total_chegadas / 30

  # ----- taxa de atendimento (atendimentos por minuto por servidor)
  mu_val = 1 / tempo_medio_atendimento

  # ----- ocupação ou utilização do sistema
  rho_val = lambda_val / (num_servidores * mu_val)

  # ----- interpretação do sistema

  if rho_val < 0.5:
    interpretacao = "Sistema SUBUTILIZADO - Há mais capacidade do que demanda"
    recomendacao = "Recomenda-se reduzir o número de servidores"
  elif 0.5 <= rho_val < 0.8:
    interpretacao = "Sistema UTILIZÁVEL"
    recomendacao = "Não é necessário aumentar o número de servidores"
  elif 0.8 <= rho_val <= 1:
    interpretacao = "Sistema SOBRECARREGADO"
    recomendacao = "Recomenda-se aumentar o número de servidores"
  else: #rho_val >= 1
    interpretacao = "Sistema em COLAPSO - A fila cresce continuamente"
    recomendacao = "Recomendação: URGENTE! Adicione mais servidores para lidar com a demanda."


  # --- apresentação dos resultados
  print("---" * 20)
  print(f"Análisede filas - {nome_servico}")
  print(f"Horário de observação : {horario_obs}")
  print("---" * 20)

  print("\nDADOS COLETADOS:")
  print(f"• Total de chegadas em 30 min: {total_chegadas} pessoas")
  print(f"• Número de servidores: {num_servidores}")
  print(f"• Tempo médio de atendimento: {tempo_medio_atendimento:.2f} minutos")

  print("\nCÁLCULOS:")
  print(f"• λ (taxa de chegada): {lambda_val:.2f} pessoas/minuto")
  print(f"• μ (taxa de atendimento por servidor): {mu_val:.2f} atendimentos/minuto")
  print(f"• ρ (ocupação do sistema): {rho_val:.2f}")

  print("\nINTERPRETAÇÃO:")
  print(f"• {interpretacao}")
  print(f"• {recomendacao}\n")


  # --- geração de gráficos
  fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14,5))

  # gráfico de chegadas por minuto
  minutos = range(1,31)
  ax1.plot(minutos, chegadas_por_minuto, marker='o', linestyle='-', color='b')
  ax1.set_title(f"Chegadas por Minuto ({horario_obs})")
  ax1.set_xlabel('Minuto')
  ax1.set_ylabel('Pessoas')
  ax1.grid(True)

  # histograma dos tempos de atendimento
  ax2.hist(tempos_atendimento, bins=5, color='green', edgecolor='green')
  ax2.set_title("Distribuição dos Tempos de Atendimento")
  ax2.set_xlabel('Tempo de Atendimento (minutos)')
  ax2.set_ylabel('Frequência')
  ax2.grid(True)

  plt.tight_layout()
  plt.show()

# --- dados para o restaurante universitário ---
dados_ru = {
    "nome_servico": "RU da Faculdade"
    ,"horario_observacao": "Horário de pico do almoço"
    ,"numero_servidores": 8
    ,"chegadas": [4, 5, 3, 2, 5, 4, 3, 4, 2, 5, 6, 4, 5, 7, 5, 6, 4, 3, 4, 3, 2, 4, 3, 2, 3, 2, 1, 2, 1, 1]
    ,"atendimentos": [1.8, 2.1, 1.9, 2.0, 2.2, 1.7, 2.3, 2.0, 1.9, 2.4, 1.8, 2.1, 2.0, 1.9, 2.2,
                   1.8, 2.0, 2.1, 1.9, 2.3, 1.7, 2.2, 2.0, 1.8, 1.9, 2.1, 2.0, 2.2, 1.9, 1.8]
}

analisar_fila(dados_ru)

"""Programa 2: Análise da Fila do Caixa de Supermercado"""

import numpy as np
import matplotlib.pyplot as plt

def analisar_fila(dados_servico):
    # --- Extração dos dados
    nome_servico = dados_servico["nome_servico"]
    horario_obs = dados_servico["horario_observacao"]
    num_servidores = dados_servico["numero_servidores"]
    chegadas_por_minuto = dados_servico["chegadas"]
    tempos_atendimento = dados_servico["atendimentos"]

    # --- Cálculos
    total_chegadas = sum(chegadas_por_minuto)
    tempo_medio_atendimento = np.mean(tempos_atendimento)
    lambda_val = total_chegadas / 30
    mu_val = 1 / tempo_medio_atendimento
    rho_val = lambda_val / (num_servidores * mu_val)

    # --- interpretação

    if rho_val < 0.5:
      interpretacao = "Sistema SUBUTILIZADO - Há mais capacidade do que demanda"
      recomendacao = "Recomenda-se reduzir o número de servidores"
    elif 0.5 <= rho_val < 0.8:
      interpretacao = "Sistema UTILIZÁVEL"
      recomendacao = "Não é necessário aumentar o número de servidores"
    elif 0.8 <= rho_val <= 1:
      interpretacao = "Sistema SOBRECARREGADO"
      recomendacao = "Recomenda-se aumentar o número de servidores"
    else: #rho_val >= 1
      interpretacao = "Sistema em COLAPSO - A fila cresce continuamente"
      recomendacao = "Recomendação: URGENTE! Adicione mais servidores para lidar com a demanda."

    # --- apresentação dos resultados
    print("---" * 20)
    print(f"Análise de filas - {nome_servico}")
    print(f"Horário de observação: {horario_obs}")
    print("---" * 20)

    print("\nDADOS COLETADOS:")
    print(f"• Total de chegadas em 30 min: {total_chegadas} pessoas")
    print(f"• Número de servidores: {num_servidores}")
    print(f"• Tempo médio de atendimento: {tempo_medio_atendimento:.2f} minutos")

    print("\nCÁLCULOS:")
    print(f"• λ (taxa de chegada): {lambda_val:.2f} pessoas/minuto")
    print(f"• μ (taxa de atendimento por servidor): {mu_val:.2f} atendimentos/minuto")
    print(f"• ρ (ocupação do sistema): {rho_val:.2f}")

    print("\nINTERPRETAÇÃO:")
    print(f"• {interpretacao}")
    print(f"• {recomendacao}\n")

    # --- geração dos gráficos
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14,5))

    minutos = range(1,31)
    ax1.plot(minutos, chegadas_por_minuto, marker='o', linestyle='-', color='orange')
    ax1.set_title(f"Chegadas por Minuto ({horario_obs})")
    ax1.set_xlabel("Minuto")
    ax1.set_ylabel("Pessoas")
    ax1.grid(True)

    ax2.hist(tempos_atendimento, bins=5, color='green', edgecolor='green')
    ax2.set_title("Distribuição dos tempos de atendimento")
    ax2.set_xlabel("Tempo de Atendimento (minutos)")
    ax2.set_ylabel("Frequência")
    ax2.grid(True)

    plt.tight_layout()
    plt.show()

# --- dados para o caixa do supermercado
dados_supermercado = {
    "nome_servico": "Caixa do Supermercado"
    ,"horario_observacao": "16h00 às 16h30"
    ,"numero_servidores": 6
    ,"chegadas": [1, 2, 1, 0, 1, 2, 1, 1, 0, 2, 1, 3, 1, 0, 1, 2, 2, 1, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 1, 2],
    "atendimentos": [2.5, 3.1, 2.8, 3.5, 2.9, 3.2, 2.7, 3.0, 3.3, 2.6, 2.9, 3.1, 3.4, 2.8, 3.0,
                   2.5, 3.2, 2.9, 3.1, 2.7, 3.3, 2.8, 3.0, 2.6, 3.4, 3.1, 2.9, 3.2, 2.8, 3.0]
}

analisar_fila(dados_supermercado)